### ISSUE TITLE
Code formatting of `commit-msg`

### ISSUE THREAD

**Issue by doldam0** [pylerAI/python-tools#11]
https://github.com/pylerAI/python-tools/blob/1bd63f02612b98d5faed894d7e2e72a923b0d2dc/.github/hooks/commit-msg#L14

Didn't black change this code like this?
```python
OK     = 'blabla'
```
to
```python
OK = 'blabla'
```
Some of pyhon developers say that the first one is not pythonic, so I recommend considering the second one.

**Comment by zzunny97** [comment]
@pylerAI/machine-learning It's very trivial, so I will handle it
