### ISSUE TITLE
Using f-string on the code of `commit-msg`

### ISSUE THREAD

**Issue by doldam0** [pylerAI/python-tools#12]
https://github.com/pylerAI/python-tools/blob/1bd63f02612b98d5faed894d7e2e72a923b0d2dc/.github/hooks/commit-msg#L38

How about using f-string instead of string concatenation?

**Comment by psycoder21** [comment]
The code owner is john

**Comment by zzunny97** [comment]
@pylerAI/machine-learning  It's very trivial, so I will handle it
