### ISSUE TITLE
Better document of `commit-msg`

### ISSUE THREAD

**Issue by doldam0** [pylerAI/python-tools#13]
https://github.com/pylerAI/python-tools/blob/1bd63f02612b98d5faed894d7e2e72a923b0d2dc/.github/hooks/commit-msg#L50

I think it will be better to specify when users get True or False, like this:
```
Returns:
    bool: Whether the tag of the commit message is valid or not.
```

**Comment by zzunny97** [comment]
Same as below

**Comment by doldam0** [comment]
Thank you for your help! 💯
