### ISSUE TITLE
ml-python-tools or python-tools ?

### ISSUE THREAD

**Issue by yakhyo** [pylerAI/python-tools#27]
## description
In `update.sh`, there is condition that checks whether is `ml-python-tools` folder or not. I am just wondering do we need to have local name of submodule  as `ml-python-tools` or `python-tools` ?
https://github.com/pylerAI/python-tools/blob/92b074586b7d3341de3c365e1e600f28a847d048/update.sh#L5

I see no harm if we change `ml-python-tools` to `python-tools`.

**Comment by Dhru1001** [comment]
#!/bin/bash

# Check if the directory name contains "python-tools"
if [[ $DIR == *"python-tools"* ]]; then
    # Perform actions for python-tools submodule
    echo "Updating python-tools submodule..."
    # Add your update commands here

else
    echo "Invalid submodule directory!"
fi

**Comment by psycoder21** [comment]
checked, this should be  `python-tools`.

**Comment by yakhyo** [comment]
I created a PR for this issue.
