### ISSUE TITLE
feat: Add commit message checker has "doc" option

### ISSUE THREAD

**Issue by zzunny97** [pylerAI/python-tools#8]
### Issue Type

Feature Request

### Source

binary

### Pytorch/Tensorflow Version

?

### Custom Code

No

### OS Platform and Distribution

?

### Python version

3.8

### GCC/Compiler version

?

### CUDA/cuDNN version

?

### GPU model and memory

?

### Overview-what is the feature?

```shell
Same as title
```

### Overview-what is the solution?

```shell
Same as title
```

### Overview-what areas of the application does this impact?

```shell
Same as title
```

### Relevant log output

```shell
?
```

**Comment by doldam0** [comment]
`doc` vs `docs`

**Comment by zzunny97** [comment]
> `doc` vs `docs`

I'm considering `doc`, because I think it seems we should have multiple change if we add "s" there. How do you think of it?

**Comment by doldam0** [comment]
> > `doc` vs `docs`
> 
> I'm considering `doc`, because I think it seems we should have multiple change if we add "s" there. How do you think of it?

The meaning of my `s` was "string" actually lol, but it could be confused
